---
abstract: 'Save constructor arguments that were not consumed.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-ExtraArgs
requires:
  Moose: 1.23
resources:
  bugtracker: https://github.com/bluefeet/MooseX-ExtraArgs/issues
  homepage: https://github.com/bluefeet/MooseX-ExtraArgs
  repository: https://github.com/bluefeet/MooseX-ExtraArgs.git
version: 0.01
